spring:
  application:
    name: monew
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false  # 자동 실행 방지

  config:
    import: optional:file:.env[.properties]

jpa:
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

task:
  scheduling:
    pool:
      size: 1