server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: monew_user
    password: monew123
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.myapp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

naver:
  api:
    client-id: ${NAVER_API_CLIENT_ID}
    client-secret: ${NAVER_API_CLIENT_SECRET}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
