spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db
    username: your_user
    password: your_password
  jpa:
    hibernate:
      ddl-auto: create  # create/update

logging:
  level:
    root: INFO
    com.myapp: DEBUG               # 코드 디버깅 위해 상세하게
    org.springframework.web: DEBUG  # HTTP 요청/응답 흐름까지
    org.hibernate.SQL: DEBUG       # 실행되는 SQL 보이게
    org.hibernate.type: TRACE      # SQL 파라미터 값까지 추적

naver:
  api:
    client-id: ${NAVER_API_CLIENT_ID}
    client-secret: ${NAVER_API_CLIENT_SECRET}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}