spring:
    application:
        name: monew
    profiles:
        active: dev

    jpa:
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

task:
    scheduling:
        pool:
            size: 1