spring:
    application:
        name: monew
    datasource:
        url: jdbc:postgresql://localhost:5432/your_db
        username: your_user
        password: your_password

    jpa:
        hibernate:
            ddl-auto: create  # 또는 update, validate 등
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

naver:
    api:
        client-id: ${NAVER_API_CLIENT_ID}
        client-secret: ${NAVER_API_CLIENT_SECRET}
