server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: monew_user
    password: monew123
  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.myapp: INFO
    org.springframework: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false

naver:
  api:
    client-id: ${NAVER_API_CLIENT_ID}
    client-secret: ${NAVER_API_CLIENT_SECRET}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
